# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dotfiles',
                'doc_host': 'https://anhvth.github.io',
                'git_url': 'https://github.com/anhvth/dotfiles',
                'lib_path': 'dotfiles'},
  'syms': {'dotfiles.core': {'dotfiles.core.foo': ('core.html#foo', 'dotfiles/core.py')}}}
