#!/bin/bash

# Autoreload Toggle Script

# Path to the IPython startup directory
# IPYTHON_STARTUP_DIR="$HOME/.ipython/profile_default/startup"

# Autoreload configuration file
AUTOLOAD_CONFIG=$HOME/.ipython/profile_default/ipython_config.py
echo $AUTOLOAD_CONFIG
# Check if argument is on or off
if [ "$1" == "on" ]; then
  cp $HOME/dotfiles/custom-tools/ipython-autoreload-on.py $AUTOLOAD_CONFIG
  # echo "%load_ext autoreload" > "$AUTOLOAD_CONFIG"
  # echo "%autoreload 2" >> "$AUTOLOAD_CONFIG"
  # echo "Autoreload enabled."
elif [ "$1" == "off" ]; then
  cp $HOME/dotfiles/custom-tools/ipython-autoreload-off.py $AUTOLOAD_CONFIG
else
  echo "Usage: $0 on/off"
fi

